#!/bin/bash
# Copyright (C) 2018 ETH Zurich and University of Bologna
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Authors: Alessandro Capotondi, University of Bologna (alessandro.capotondi@unibo.it)
#
# This script build the GCC 7.1.1 toolchain for the HERO host

# Error handler
set -e
trap 'previous_command=$this_command; this_command=$BASH_COMMAND' DEBUG
trap 'echo $0: ERROR "$previous_command" failed at line $LINENO' ERR

if [[ ! -f "${0##*/}" ]]; then
    echo "Error: ${0##*/} should be launched from the directory that contains it"
    exit 1
fi

# Setup the envioronmental variables
source scripts/hero_arm_toolchain_env.sh

# Local envioronmental variables definition
HERO_PARALLEL_BUILD=
SYSROOT=${HERO_GCC_INSTALL_DIR}/${HERO_HOST_TARGET}/libc


show_help() {
cat << EOF
Usage: ${0##*/} [-P|-T]|[-hblcgs]] [-jdx]

HERO Host-side toolchain builder tool:
----------------------------------------------------

Combined commands
----------------------------------------------------

    -T : COMPILE all modules for HERO toolchain:
              > binutils
              > only-gcc
              > glibc
              > gcc with accelerator
    -P : COMPILE all modules for ARM-only toolchain:
              > binutils
              > only-gcc
              > glibc
              > gcc standalone

Options
----------------------------------------------------
    -x : REMOVE build files
    -d : DOWNLOAD source files
    -j : parallel make ENABLED


Advanced commands
----------------------------------------------------
    -h : display this help and exit
    -b : COMPILE binutils
    -l : COMPILE glibc
    -c : COMPILE only-gcc (stage 1)
    -g : COMPILE gcc with accelerator (stage 3)
    -s : COMPILE gcc standalone (stage 2)
    -o : COMPILE libgomp (stage 3)

EOF
}

get_sources() {
    . ${HERO_TOOLCHAIN_DIR}/scripts/hero_toolchain_get_sources.sh
}

build_binutils() {
    mkdir -p ${HERO_HOST_GCC_BUILD_DIR}/binutils
    cd ${HERO_HOST_GCC_BUILD_DIR}/binutils
    ${HERO_HOST_SRC_DIR}/binutils/configure --target=${HERO_HOST_TARGET} --prefix=${HERO_GCC_INSTALL_DIR} --disable-multilib --disable-nls --disable-werror --with-sysroot=${SYSROOT}
    make all ${HERO_PARALLEL_BUILD}
    make install
}

build_glibc() {
    export LD_LIBRARY_PATH_BACKUP=$LD_LIBRARY_PATH
    unset LD_LIBRARY_PATH

    # Standard C Library Headers and Startup Files
    mkdir -p ${HERO_HOST_GCC_BUILD_DIR}/glibc
    cd ${HERO_HOST_GCC_BUILD_DIR}/glibc

    ${HERO_HOST_SRC_DIR}/${HERO_HOST_GLIBC}/configure --prefix=/usr --build=$MACHTYPE --host=${HERO_HOST_TARGET} --target=${HERO_HOST_TARGET} --with-headers=${SYSROOT}/usr/include --disable-multilib --disable-nls --disable-werror libc_cv_forced_unwind=yes --enable-obsolete-rpc
    make install-headers install_root=${SYSROOT} install-bootstrap-headers=yes
    make $HERO_PARALLEL_BUILD csu/subdir_lib
    mkdir -p ${SYSROOT}/usr/lib
    install csu/crt1.o csu/crti.o csu/crtn.o ${SYSROOT}/usr/lib
    ${HERO_HOST_TARGET}-gcc -nostdlib -nostartfiles -shared -x c /dev/null -o ${SYSROOT}/usr/lib/libc.so
    touch ${SYSROOT}/usr/include/gnu/stubs.h
    cp -a bits/stdio_lim.h ${SYSROOT}/usr/include/bits/
    cd ..

    # Compiler Support Library
    cd ${HERO_HOST_GCC_BUILD_DIR}/gcc-stage1
    make all-target-libgcc ${HERO_PARALLEL_BUILD}
    make install-target-libgcc
 
    # Standard C Library & the rest of Glibc
    cd ${HERO_HOST_GCC_BUILD_DIR}/glibc
    make ${HERO_PARALLEL_BUILD}
    make install install_root=${SYSROOT}
    cd ..

    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH_BACKUP
    unset LD_LIBRARY_PATH_BACKUP
}

build_gcc_stage1() {
    cd $HERO_HOST_LINUX_KERNEL_DIR
    make ARCH=${HERO_HOST_LINUX_ARCH} INSTALL_HDR_PATH=${SYSROOT}/usr headers_install  
    #cp -a include/linux include/asm-generic ${SYSROOT}/usr/include/
    #cp -a include/asm-${HERO_HOST_LINUX_ARCH} ${SYSROOT}/usr/include/asm   

    mkdir -p ${HERO_HOST_GCC_BUILD_DIR}/gcc-stage1
    cd ${HERO_HOST_GCC_BUILD_DIR}/gcc-stage1
    ${HERO_HOST_GCC_SRC_DIR}/configure --prefix=${HERO_GCC_INSTALL_DIR} --target=${HERO_HOST_TARGET} --with-arch=armv7-a ${HERO_HOST_FPU_CONFIG} --with-mode=thumb --enable-languages=c --disable-multilib --disable-nls --disable-werror --disable-sjlj-exceptions --with-sysroot=${SYSROOT}
    make all-gcc ${HERO_PARALLEL_BUILD}
    make install-gcc ${HERO_PARALLEL_BUILD}

    if [ $? -ne 0 ]; then
        echo "ERROR: build_gcc_stage1 failed, aborting now."
        exit 1
    fi
}

build_gcc_stage2() {
    mkdir -p ${HERO_HOST_GCC_BUILD_DIR}/gcc-stage2
    cd ${HERO_HOST_GCC_BUILD_DIR}/gcc-stage2
    ensure_clean_libgomp_build
    ${HERO_HOST_GCC_SRC_DIR}/configure --prefix=${HERO_GCC_INSTALL_DIR} --target=${HERO_HOST_TARGET} --with-arch=armv7-a ${HERO_HOST_FPU_CONFIG} --with-mode=thumb --enable-languages=c,c++,lto --disable-multilib --disable-nls --disable-werror --disable-sjlj-exceptions --with-sysroot=${SYSROOT}
    make all ${HERO_PARALLEL_BUILD}
    make install ${HERO_PARALLEL_BUILD}

    if [ $? -ne 0 ]; then
        echo "ERROR: build_gcc_stage2 failed, aborting now."
        exit 1
    fi
}

ensure_clean_libgomp_build() {
    if [ -d "arm-linux-gnueabihf/libgomp/" ]; then
        echo "Cleaning up libgomp build folder."
        rm -rf arm-linux-gnueabihf/libgomp/*
    fi
}

build_gcc_stage3() {
    mkdir -p ${HERO_HOST_GCC_BUILD_DIR}/gcc-stage3
    cd ${HERO_HOST_GCC_BUILD_DIR}/gcc-stage3
    ensure_clean_libgomp_build
    ${HERO_HOST_GCC_SRC_DIR}/configure --prefix=${HERO_GCC_INSTALL_DIR} --target=${HERO_HOST_TARGET} --enable-offload-targets=riscv32-unknown-elf=${HERO_GCC_INSTALL_DIR} --with-arch=armv7-a ${HERO_HOST_FPU_CONFIG} --with-mode=thumb --enable-languages=c,c++,lto --disable-multilib --disable-nls --disable-werror --disable-sjlj-exceptions --with-sysroot=${SYSROOT}
    make all-gcc ${HERO_PARALLEL_BUILD}  
    make all-target-libstdc++-v3 ${HERO_PARALLEL_BUILD}
    ensure_clean_libgomp_build
    make all ${HERO_PARALLEL_BUILD}
    make install ${HERO_PARALLEL_BUILD}

    if [ $? -ne 0 ]; then
        echo "ERROR: build_gcc_stage3 failed, aborting now."
        exit 1
    fi
}

build_libgomp() {
    cd ${HERO_HOST_GCC_BUILD_DIR}/gcc-stage3
    ensure_clean_libgomp_build
    make all ${HERO_PARALLEL_BUILD}
    make install ${HERO_PARALLEL_BUILD}

    if [ $? -ne 0 ]; then
        echo "ERROR: build_libgomp failed, aborting now."
        exit 1
    fi
}

#
# Main function start HERE
#

do_get_sources=false
do_remove_all=false
do_compile_binutils=false
do_compile_glibc=false
do_compile_cc=false
do_compile_gcc=false
do_compile_gcc_with_accelerator=false
do_compile_libgomp=false

while getopts PThblcgsjdxo opt; do
    case $opt in
        h)
            show_help
            if [[ "$_" = "$0" ]]; then
                exit 0
            fi
            ;;
        b)  do_compile_binutils=true
            ;;
        l)  do_compile_glibc=true
            ;;
        c)  do_compile_cc=true
            ;;
        s)  do_compile_gcc=true
            ;;
        g)  do_compile_gcc_with_accelerator=true
            ;;
        x)  do_remove_all=true
            ;;
        d)  do_get_sources=true
            ;;
        j)  if [ -z "${HERO_MAX_PARALLEL_BUILD_JOBS}" ]; then
                HERO_PARALLEL_BUILD=-j`nproc`
            else
                HERO_PARALLEL_BUILD=-j${HERO_MAX_PARALLEL_BUILD_JOBS}
            fi
            ;;
        T)  do_compile_binutils=true
            do_compile_cc=true
            do_compile_glibc=true
            do_compile_gcc_with_accelerator=true
            do_compile_gcc=false
            ;;
        P)  do_compile_binutils=true
            do_compile_cc=true
            do_compile_glibc=true
            do_compile_gcc_with_accelerator=false
            do_compile_gcc=true
            ;;
        o)  do_compile_libgomp=true
            ;;
        *)
            show_help >&2
            if [[ "$_" = "$0" ]]; then
                exit 1
            fi
            ;;
    esac
done

if [[ $# -eq 0 ]] ; then
    show_help
    if [[ "$_" = "$0" ]]; then
        exit 0
    fi
fi

# Get sources
if [ "$do_get_sources" = true ] ; then
    get_sources
fi

if [ "$do_remove_all" = true ] ; then
    rm -rf ${HERO_HOST_GCC_BUILD_DIR}
fi

# Build binutils
if [ "$do_compile_binutils" = true ] ; then
    build_binutils
fi

# Build gcc (stage 1)
if [ "$do_compile_cc" = true ] ; then
    build_gcc_stage1
fi

if [ "$do_compile_glibc" = true ] ; then
    build_glibc
fi

# Build GCC (stage 2)
if [ "$do_compile_gcc" = true ] ; then
    build_gcc_stage2
fi

# Build GCC (stage 3)
if [ "$do_compile_gcc_with_accelerator" = true ] ; then
    build_gcc_stage3
fi

# Build Libgomp
if [ "$do_compile_libgomp" = true ] ; then
    build_libgomp
fi

echo "Done!"
# That's all folks!!
